version: 2.1

jobs:
  run-tests:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run Go Unit Tests
          command: go test -v ./...

  build-and-push:
    docker:
      - image: docker:latest

    environment:
      IMAGE_NAME: harkirat101803/suricata-opa-listener

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to DockerHub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build the Docker image
          command: docker build -t $IMAGE_NAME:latest -f dockerfile .
      - run:
          name: Push Docker image to Docker Hub
          command: docker push $IMAGE_NAME:latest

workflows:
  build-deploy:
    jobs:
      - run-tests
      - build-and-push:
          requires:
            - run-tests
